name: Build on Commit
on:
  push:
    branches:
      - linty
  pull_request:

jobs:
  build:
    name: Build on Commit
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Graphviz
        run: sudo apt install graphviz

      - name: Set Up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Build and Run Unit Tests
        run: mvn -B clean install
